// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0oe3YALJPNtIBvjBA4ebObH7DJ5AmVu8',
    appId: '1:566070551824:web:32f336f0d0a9804049b195',
    messagingSenderId: '566070551824',
    projectId: 'chat-app-e5c95',
    authDomain: 'chat-app-e5c95.firebaseapp.com',
    storageBucket: 'chat-app-e5c95.appspot.com',
    measurementId: 'G-H3J5DBPMJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-fkItK6uQ-DK5IkPbp7uZR7L6YEdxLOk',
    appId: '1:566070551824:android:340cf27c7c5256a049b195',
    messagingSenderId: '566070551824',
    projectId: 'chat-app-e5c95',
    storageBucket: 'chat-app-e5c95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb7iI8IYGfCi4l5SMKDxt0iUNu9KcLdvo',
    appId: '1:566070551824:ios:6c0032ffae79606649b195',
    messagingSenderId: '566070551824',
    projectId: 'chat-app-e5c95',
    storageBucket: 'chat-app-e5c95.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb7iI8IYGfCi4l5SMKDxt0iUNu9KcLdvo',
    appId: '1:566070551824:ios:af7fdb3cfe81cbe249b195',
    messagingSenderId: '566070551824',
    projectId: 'chat-app-e5c95',
    storageBucket: 'chat-app-e5c95.appspot.com',
    iosBundleId: 'com.example.chatAppFirebase.RunnerTests',
  );
}
